<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-03T16:07:05 IST" name="Suite" finished-at="2023-09-03T16:07:27 IST" duration-ms="22098">
    <groups>
    </groups>
    <test started-at="2023-09-03T16:07:05 IST" name="Test" finished-at="2023-09-03T16:07:27 IST" duration-ms="22098">
      <class name="com.amazon.testcase.E2E_Flow">
        <test-method is-config="true" signature="reportGeneration()[pri:0, instance:com.amazon.testcase.E2E_Flow@6aba2b86]" started-at="2023-09-03T16:07:05 IST" name="reportGeneration" finished-at="2023-09-03T16:07:05 IST" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportGeneration -->
        <test-method is-config="true" signature="intializeBrowser()[pri:0, instance:com.amazon.testcase.E2E_Flow@6aba2b86]" started-at="2023-09-03T16:07:05 IST" name="intializeBrowser" finished-at="2023-09-03T16:07:08 IST" duration-ms="3008" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intializeBrowser -->
        <test-method signature="OneTest()[pri:1, instance:com.amazon.testcase.E2E_Flow@6aba2b86]" started-at="2023-09-03T16:07:08 IST" name="OneTest" finished-at="2023-09-03T16:07:08 IST" duration-ms="408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OneTest -->
        <test-method signature="TwoTest()[pri:2, instance:com.amazon.testcase.E2E_Flow@6aba2b86]" started-at="2023-09-03T16:07:08 IST" name="TwoTest" finished-at="2023-09-03T16:07:10 IST" duration-ms="2014" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TwoTest -->
        <test-method signature="ThreeTest()[pri:3, instance:com.amazon.testcase.E2E_Flow@6aba2b86]" started-at="2023-09-03T16:07:11 IST" name="ThreeTest" finished-at="2023-09-03T16:07:16 IST" duration-ms="5251" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ThreeTest -->
        <test-method signature="FourTest()[pri:4, instance:com.amazon.testcase.E2E_Flow@6aba2b86]" started-at="2023-09-03T16:07:16 IST" name="FourTest" finished-at="2023-09-03T16:07:26 IST" duration-ms="10328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FourTest -->
        <test-method signature="FiveTest()[pri:0, instance:com.amazon.testcase.E2E_Flow@6aba2b86]" started-at="2023-09-03T16:07:27 IST" name="FiveTest" finished-at="2023-09-03T16:07:27 IST" depends-on-methods="com.amazon.testcase.E2E_Flow.FourTest" duration-ms="121" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at com.amazon.testcase.E2E_Flow.FiveTest(E2E_Flow.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FiveTest -->
        <test-method signature="SixTest()[pri:0, instance:com.amazon.testcase.E2E_Flow@6aba2b86]" started-at="2023-09-03T16:07:27 IST" name="SixTest" finished-at="2023-09-03T16:07:27 IST" depends-on-methods="com.amazon.testcase.E2E_Flow.FiveTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.amazon.testcase.E2E_Flow.SixTest() on instance com.amazon.testcase.E2E_Flow@6aba2b86 depends on not successfully finished methods 
[com.amazon.testcase.E2E_Flow.FiveTest() on instance com.amazon.testcase.E2E_Flow@6aba2b86]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.amazon.testcase.E2E_Flow.SixTest() on instance com.amazon.testcase.E2E_Flow@6aba2b86 depends on not successfully finished methods 
[com.amazon.testcase.E2E_Flow.FiveTest() on instance com.amazon.testcase.E2E_Flow@6aba2b86]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SixTest -->
        <test-method is-config="true" signature="closingBrowser()[pri:0, instance:com.amazon.testcase.E2E_Flow@6aba2b86]" started-at="2023-09-03T16:07:27 IST" name="closingBrowser" finished-at="2023-09-03T16:07:27 IST" duration-ms="68" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingBrowser -->
        <test-method is-config="true" signature="closingReport()[pri:0, instance:com.amazon.testcase.E2E_Flow@6aba2b86]" started-at="2023-09-03T16:07:27 IST" name="closingReport" finished-at="2023-09-03T16:07:27 IST" duration-ms="289" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingReport -->
      </class> <!-- com.amazon.testcase.E2E_Flow -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
